"""Add language column to users table

Revision ID: 1be35586f835
Revises: 5ebc48e65e28
Create Date: 2025-10-15 00:23:31.343665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be35586f835'
down_revision: Union[str, None] = '5ebc48e65e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add language column to users table
    # Check if column exists first (for databases that may already have it)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]

    if 'language' not in columns:
        op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False, server_default='pl'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove language column from users table
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
