"""Add quiz tags, draft status and archived status

Revision ID: 539e99dce524
Revises: 1be35586f835
Create Date: 2025-10-15 08:44:35.135361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539e99dce524'
down_revision: Union[str, None] = '1be35586f835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Create tags table if it doesn't exist
    if 'tags' not in inspector.get_table_names():
        op.create_table('tags',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=50), nullable=False),
            sa.Column('color', sa.String(length=7), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name', name='uq_tag_name')
        )
        op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
        op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)

    # Create quiz_tags association table if it doesn't exist
    if 'quiz_tags' not in inspector.get_table_names():
        op.create_table('quiz_tags',
            sa.Column('quiz_id', sa.Integer(), nullable=False),
            sa.Column('tag_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('quiz_id', 'tag_id')
        )

    # Check if columns already exist before adding them
    columns = [col['name'] for col in inspector.get_columns('quizzes')]

    if 'is_draft' not in columns:
        op.add_column('quizzes', sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='1'))

    if 'status' not in columns:
        op.add_column('quizzes', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'status')
    op.drop_column('quizzes', 'is_draft')
    op.drop_table('quiz_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
