"""Add icon field to Quiz model

Revision ID: aabc7fb28dd6
Revises: 7811cd69690d
Create Date: 2025-10-16 18:37:59.213906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabc7fb28dd6'
down_revision: Union[str, None] = '7811cd69690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'icon')
    # ### end Alembic commands ###
